"""Projection (read model) endpoints: stats, entity lookup, current location.

These queries go straight to the materialized read model - no ontology, no
SPARQL. The operational query path must never pay for semantic complexity it
does not need; this router is the live demonstration of that rule.
"""

from __future__ import annotations

import json
import threading
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, HTTPException, Query

from foundry.console.api.monitor import event_log_path
from foundry.events import EventLog
from foundry.projector import Projector, replay_log
from foundry.readmodel import ReadModel, format_instant, parse_instant

BENCHMARK_REPORT = Path(__file__).resolve().parents[3] / "build" / "benchmark-report.json"

router = APIRouter(prefix="/projection", tags=["projection"])


@router.get("/benchmark")
def projection_benchmark() -> dict:
    """Return the latest benchmark report generated by `tools/benchmark.py`."""
    if not BENCHMARK_REPORT.exists():
        raise HTTPException(
            status_code=404,
            detail="No benchmark report found; run `make benchmark` first",
        )
    try:
        return json.loads(BENCHMARK_REPORT.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=500, detail=f"corrupt benchmark report: {exc}") from exc


_model_cache: ReadModel | None = None
_model_log_mtime: float | None = None
_model_lock = threading.Lock()


def _snapshot_paths(log_path: Path) -> tuple[Path, Path]:
    """Sidecar paths next to the log: pickled model + its fingerprint meta."""
    return (
        log_path.with_suffix(log_path.suffix + ".readmodel.pkl"),
        log_path.with_suffix(log_path.suffix + ".readmodel.json"),
    )


def _read_model() -> ReadModel:
    """Read model cached in-process and on disk, resumed incrementally.

    Layers:
    1. in-process cache keyed by log mtime — the common hit;
    2. persisted snapshot + checkpoint (B2/B6): a log change applies only the
       suffix after the recorded sequence, and a server restart loads the
       snapshot instead of replaying the whole log;
    3. anything missing or corrupt degrades to a full replay — the snapshot is
       a cache, never a source of truth (ADR-0002/0004).
    """
    global _model_cache, _model_log_mtime
    with _model_lock:
        path = event_log_path()
        if not path.exists():
            _model_cache = ReadModel()
            _model_log_mtime = None
            return _model_cache

        current_mtime = path.stat().st_mtime
        if _model_cache is not None and _model_log_mtime == current_mtime:
            return _model_cache

        snapshot_path, meta_path = _snapshot_paths(path)
        size = path.stat().st_size
        model = ReadModel.load_snapshot(snapshot_path)
        meta: dict = {}
        if model is not None and snapshot_path.exists():
            try:
                meta = json.loads(meta_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                meta = {}

        checkpoint = model.checkpoint_sequence if model is not None else None
        grew = (
            model is not None
            and checkpoint is not None
            and meta.get("checkpoint_sequence") == checkpoint
            and meta.get("log_size") is not None
            and size >= meta["log_size"]
        )
        if grew:
            # append-only growth: fold in only what came after the checkpoint
            events = EventLog(path).read_all()  # validates the entire log
            Projector(model).replay(events, after_sequence=checkpoint)
        else:
            model, _stats = replay_log(EventLog(path))

        model.save_snapshot(snapshot_path)
        meta_path.write_text(
            json.dumps({"checkpoint_sequence": model.checkpoint_sequence, "log_size": size}) + "\n",
            encoding="utf-8",
        )
        _model_cache = model
        _model_log_mtime = current_mtime
        return _model_cache


def reset_cache() -> None:
    """Invalidate the cached model (used by tests)."""
    global _model_cache, _model_log_mtime
    with _model_lock:
        _model_cache = None
        _model_log_mtime = None


@router.get("")
def projection_stats() -> dict:
    """Projection health: counts, freshness, and lag vs the 5s SLO."""
    model = _read_model()
    stats = model.stats()
    lag = stats["lag_seconds"]
    return {
        "exists": event_log_path().exists(),
        "slo_lag_seconds": 5,
        "within_slo": None if lag is None else lag <= 5.0,
        **stats,
    }


@router.get("/entities/{entity_id}")
def entity_by_id(entity_id: str) -> dict:
    """Q1 point lookup against the read model."""
    view = _read_model().get_entity(entity_id)
    if view is None:
        raise HTTPException(status_code=404, detail=f"unknown entity {entity_id}")
    location = _read_model().current_location(entity_id)
    return {
        "entity": {
            "entity_id": view.entity_id,
            "entity_type": view.entity_type,
            "name": view.name,
            "first_seen": view.first_seen,
            "last_event_time": view.last_event_time,
        },
        "current_location": (
            {
                "location_uri": location.location_uri,
                "as_of": location.as_of,
                "source_ids": list(location.source_ids),
            }
            if location
            else None
        ),
    }


@router.get("/lookup")
def entity_lookup(name: Annotated[str, Query(min_length=1)]) -> dict:
    """Name lookup returning canonical ids (read-model only)."""
    hits = _read_model().find_by_name(name)
    return {
        "query": name,
        "matches": [
            {
                "entity_id": view.entity_id,
                "entity_type": view.entity_type,
                "name": view.name,
            }
            for view in hits
        ],
    }


@router.get("/entities/{entity_id}/location/as-of")
def location_as_of(entity_id: str, at: str) -> dict:
    """Q4 temporal query: location of an entity at a given instant."""
    try:
        instant = parse_instant(at)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    fact = _read_model().location_as_of(entity_id, instant)
    return {
        "entity_id": entity_id,
        "at": format_instant(instant),
        "location": (
            {
                "location_uri": fact.location_uri,
                "as_of": fact.as_of,
                "source_ids": list(fact.source_ids),
            }
            if fact
            else None
        ),
    }
