"""Projection (read model) endpoints: stats, entity lookup, current location.

These queries go straight to the materialized read model - no ontology, no
SPARQL. The operational query path must never pay for semantic complexity it
does not need; this router is the live demonstration of that rule.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, HTTPException, Query

from foundry.console.api.monitor import event_log_path
from foundry.events import EventLog
from foundry.projector import replay_log
from foundry.readmodel import ReadModel, format_instant, parse_instant

BENCHMARK_REPORT = Path(__file__).resolve().parents[3] / "build" / "benchmark-report.json"

router = APIRouter(prefix="/projection", tags=["projection"])


@router.get("/benchmark")
def projection_benchmark() -> dict:
    """Return the latest benchmark report generated by `tools/benchmark.py`."""
    if not BENCHMARK_REPORT.exists():
        raise HTTPException(
            status_code=404,
            detail="No benchmark report found; run `make benchmark` first",
        )
    try:
        return json.loads(BENCHMARK_REPORT.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=500, detail=f"corrupt benchmark report: {exc}") from exc


_model_cache: ReadModel | None = None
_model_log_mtime: float | None = None


def _read_model() -> ReadModel:
    """Replay the log into a fresh model, cached by log file mtime."""
    global _model_cache, _model_log_mtime
    path = event_log_path()
    if not path.exists():
        _model_cache = ReadModel()
        _model_log_mtime = None
        return _model_cache
    mtime = path.stat().st_mtime
    if _model_cache is None or _model_log_mtime != mtime:
        _model_cache, _stats = replay_log(EventLog(path))
        _model_log_mtime = mtime
    return _model_cache


def reset_cache() -> None:
    """Invalidate the cached model (used by tests)."""
    global _model_cache, _model_log_mtime
    _model_cache = None
    _model_log_mtime = None


@router.get("")
def projection_stats() -> dict:
    """Projection health: counts, freshness, and lag vs the 5s SLO."""
    model = _read_model()
    stats = model.stats()
    lag = stats["lag_seconds"]
    return {
        "exists": event_log_path().exists(),
        "slo_lag_seconds": 5,
        "within_slo": None if lag is None else lag <= 5.0,
        **stats,
    }


@router.get("/entities/{entity_id}")
def entity_by_id(entity_id: str) -> dict:
    """Q1 point lookup against the read model."""
    view = _read_model().get_entity(entity_id)
    if view is None:
        raise HTTPException(status_code=404, detail=f"unknown entity {entity_id}")
    location = _read_model().current_location(entity_id)
    return {
        "entity": {
            "entity_id": view.entity_id,
            "entity_type": view.entity_type,
            "name": view.name,
            "first_seen": view.first_seen,
            "last_event_time": view.last_event_time,
        },
        "current_location": (
            {
                "location_uri": location.location_uri,
                "as_of": location.as_of,
                "source_ids": list(location.source_ids),
            }
            if location
            else None
        ),
    }


@router.get("/lookup")
def entity_lookup(name: Annotated[str, Query(min_length=1)]) -> dict:
    """Name lookup returning canonical ids (read-model only)."""
    hits = _read_model().find_by_name(name)
    return {
        "query": name,
        "matches": [
            {
                "entity_id": view.entity_id,
                "entity_type": view.entity_type,
                "name": view.name,
            }
            for view in hits
        ],
    }


@router.get("/entities/{entity_id}/location/as-of")
def location_as_of(entity_id: str, at: str) -> dict:
    """Q4 temporal query: location of an entity at a given instant."""
    try:
        instant = parse_instant(at)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    fact = _read_model().location_as_of(entity_id, instant)
    return {
        "entity_id": entity_id,
        "at": format_instant(instant),
        "location": (
            {
                "location_uri": fact.location_uri,
                "as_of": fact.as_of,
                "source_ids": list(fact.source_ids),
            }
            if fact
            else None
        ),
    }
